require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true

Style/GuardClause:
  MinBodyLength: 2

Layout/LineLength:
  AutoCorrect: true
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
